services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Lizismee2710@
    depends_on:
      - db
    stdin_open: true # Enable `docker attach`
    tty: true

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library_management_system_development
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
