app_name: "VLIB"
author:
  max_length: 30
book:
  name:
    max_length: 100
  description:
    max_length: 1000
  min_in_stock: 0
  default_cover: "DefaultCover.png"
comment:
  max_length: 100
image:
  max_size: 5
  allow_type: "image/jpeg, image/gif, image/png"
username:
  max_length: 20
email:
  format: "\\A[\\w+\\-.]+@[a-z\\d\\-.]+\\.[a-z]+\\z"
  max_length: 256
phone_length: 10
default_avatar:
  link: "DefaultAvatar.png"
  alt: "Profile"
VN_flag:
  link: "VN_flag.png"
  alt: "vi"
EN_flag:
  link: "EN_flag.png"
  alt: "en"
default_email: "noreply@demomailtrap.com"
demo_email: "nguyen.the.vu-b@sun-asterisk.com"
default_pagination: 10
request:
  allow_amount: 5
  max_borrow_days: 30
devise:
  stretch:
    test: 1
    other: 12
  password:
    min_length: 8
    max_length: 20
  max_attempts: 5
  unlock_in: 1
  reset_password_within: 6
jwt_default_exp: 12
default_shard: 1
